### ISSUE TITLE
Replicator crashing on push

### ISSUE THREAD

**Issue by paulJordaan** [cloudant/CDTDatastore#385] opened 2017-09-07 18:38 UTC
I am experiencing the following error:

When pulling a rather large data set the app crashes with the following log: 
[com.paragon.dfect_issue_40_crash_.txt](https://github.com/cloudant/CDTDatastore/files/1285748/com.paragon.dfect_issue_40_crash_.txt)

The code for the pull replication is as follows:

```
-(void)pullReplication:(NSString *)projectId
{
    [self log:@"Starting pull replication"];
    [UIApplication sharedApplication].idleTimerDisabled = YES;
    
    NSURL *url = [self replicatorURL];
    
    AppDelegate *delegate = (AppDelegate *)[[UIApplication sharedApplication] delegate];
    CDTReplicatorFactory *factory = delegate.replicatorFactory;
    CDTPullReplication * replicationConfig = [CDTPullReplication replicationWithSource:url
                                                                                target:delegate.datastore];
    NSError *error;
    replicationConfig.filter = @"loopback/project";
    replicationConfig.filterParams = @{@"projectId":projectId};  
    CDTReplicator *aPullReplicator = [factory oneWay:replicationConfig error:&error];
    if (!aPullReplicator) {
        [self log:@"Error creating pull replicator: %@", error];
    }
    else {
        [self startAndFollowReplicator:aPullReplicator label:@"pull"];
    }
}

-(void)startAndFollowReplicator:(CDTReplicator*)replicator label:(NSString*)label {  
    NSString *state = [CDTReplicator stringForReplicatorState:replicator.state];
    [self log:@"%@ state: %@ (%d)", label, state, replicator.state];
 
    [replicator setDelegate:self];
    
    NSError *error;
    if (![replicator startWithError:&error]) {
        [self log:@"error starting %@ replicator: %@", label, error];
        state = [CDTReplicator stringForReplicatorState:replicator.state];
        [self log:@"%@ state: %@ (%d)", label, state, replicator.state];
        return;
    }  
    @synchronized(self){
        [self.replicators addObject:replicator];
    }
}
```

**Comment by tomblench** [comment] 2017-09-08 08:11
@paulJordaan have you got a minimal reproducible test case? There are lots of other threads for UI etc in that stacktrace.

It also seems a bit odd that thread #8 "TDReplicator: repl047" has QuartzCore/UIKit calls on it. I don't think there should be any UI calls on this thread.

**Comment by paulJordaan** [comment] 2017-09-08 10:11
@tomblench I will try to put together a test case over the weekend. The mention of the UI threads has pointed me in the direction of a possible cause. Will investigate and report back. Thanks!

**Comment by paulJordaan** [comment] 2017-09-10 08:25
@tomblench it's difficult to put together a test case as this is happening with a specific data set which I can not share.

I've removed the UIKit calls inside the replicator for a cleaner log
[com.paragon.dfect_issue_15_crash_4c4441a9891841a893f3a5b9d184c632_6834a9c695aa11e7a71556847afe9799_0_v2.txt](https://github.com/cloudant/CDTDatastore/files/1290365/com.paragon.dfect_issue_15_crash_4c4441a9891841a893f3a5b9d184c632_6834a9c695aa11e7a71556847afe9799_0_v2.txt)

I've also looked at the live log from the device, see below. 

```
Sep 10 10:10:47 PI-iPad-04 D-Fect(CoreFoundation)[342] <Notice>: *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '_bufferLength > 0'
*** First throw call stack:
(0x186462fe0 0x184ec4538 0x186462eb4 0x186efb760 0x1001b17ac 0x1001a0f14 0x1001a10a8 0x186f40c4c 0x186411aa4 0x1864117a8 0x186411068 0x18640ec8c 0x18633eda4 0x186e59db4 0x1001ab52c 0x186f57318 0x18552568c 0x18552559c 0x185522cb4)
Sep 10 10:10:47 PI-iPad-04 SpringBoard(KeyboardArbiter)[49] <Error>: HW kbd: Failed to set (null) as keyboard focus
Sep 10 10:10:47 PI-iPad-04 nsurlsessiond[112] <Error>: Task 47 for client <private> completed with error - code: -997
Sep 10 10:10:47 PI-iPad-04 nsurlsessiond[112] <Error>: Task 56 for client <private> completed with error - code: -997
Sep 10 10:10:47 PI-iPad-04 nsurlsessiond(CFNetwork)[112] <Notice>: TIC TCP Conn Cancel [337:0x107475540]
Sep 10 10:10:47 PI-iPad-04 nsurlsessiond(CFNetwork)[112] <Notice>: TIC TCP [0x107475540] canceling activity 0x10735b0f0
Sep 10 10:10:47 PI-iPad-04 nsurlsessiond(CFNetwork)[112] <Notice>: TIC TCP Conn Cancel [334:0x107399490]
Sep 10 10:10:47 PI-iPad-04 nsurlsessiond(CFNetwork)[112] <Notice>: TIC TCP [0x107399490] completing activity 0x10738cf80
Sep 10 10:10:47 PI-iPad-04 DuetHeuristic-BM(DuetActivitySchedulerDaemon)[110] <Notice>: CANCELED: <private>!
Sep 10 10:10:47 PI-iPad-04 DuetHeuristic-BM(DuetActivitySchedulerDaemon)[110] <Notice>: Stop network path monitoring for '<private>'
Sep 10 10:10:47 PI-iPad-04 DuetHeuristic-BM(DuetActivitySchedulerDaemon)[110] <Notice>: COMPLETED <private>!
Sep 10 10:10:47 PI-iPad-04 DuetHeuristic-BM(DuetActivitySchedulerDaemon)[110] <Notice>: Stop network path monitoring for '<private>'
Sep 10 10:10:47 PI-iPad-04 DuetHeuristic-BM(DuetActivitySchedulerDaemon)[110] <Notice>: NO LONGER RUNNING <private> ...Tasks running in group [<private>] are 2!
Sep 10 10:10:47 PI-iPad-04 backboardd[52] <Notice>: Turning off orientation events.
Sep 10 10:10:47 PI-iPad-04 nsurlsessiond(CFNetwork)[112] <Error>: NSURLSessionTask finished with error - code: -999
Sep 10 10:10:47 PI-iPad-04 nsurlsessiond(CFNetwork)[112] <Error>: NSURLSessionTask finished with error - code: -999
Sep 10 10:10:47 PI-iPad-04 nsurlsessiond(CFNetwork)[112] <Notice>: TIC TCP Conn Destroyed [334:0x107399490]
Sep 10 10:10:47 PI-iPad-04 nsurlsessiond[112] <Error>: Task 9 for client <private> completed with error - code: -997
Sep 10 10:10:47 PI-iPad-04 nsurlsessiond(CFNetwork)[112] <Notice>: TIC TCP Conn Cancel [336:0x107365e20]
Sep 10 10:10:47 PI-iPad-04 nsurlsessiond(CFNetwork)[112] <Notice>: TIC TCP [0x107365e20] completing activity 0x10739cac0
Sep 10 10:10:47 PI-iPad-04 nsurlsessiond(CFNetwork)[112] <Error>: HTTP load failed (error code: -999 [1:89])
Sep 10 10:10:47 PI-iPad-04 nsurlsessiond(CFNetwork)[112] <Notice>: TIC TCP Conn Destroyed [336:0x107365e20]
Sep 10 10:10:47 PI-iPad-04 nsurlsessiond(CFNetwork)[112] <Error>: NSURLSessionTask finished with error - code: -999
Sep 10 10:10:47 PI-iPad-04 DuetHeuristic-BM(DuetActivitySchedulerDaemon)[110] <Notice>: COMPLETED <private>!
Sep 10 10:10:47 PI-iPad-04 backboardd(BaseBoard)[52] <Error>: Unable to get short BSD proc info for 342: No such process
Sep 10 10:10:47 PI-iPad-04 backboardd(BaseBoard)[52] <Error>: Unable to get proc info for 342: No such process
Sep 10 10:10:47 PI-iPad-04 DuetHeuristic-BM(DuetActivitySchedulerDaemon)[110] <Notice>: Stop network path monitoring for '<private>'
Sep 10 10:10:47 PI-iPad-04 DuetHeuristic-BM(DuetActivitySchedulerDaemon)[110] <Notice>: NO LONGER RUNNING <private> ...Tasks running in group [<private>] are 1!
Sep 10 10:10:47 PI-iPad-04 backboardd(CoreMotion)[52] <Notice>: Stopping orientation detection.
Sep 10 10:10:47 PI-iPad-04 ReportCrash(CrashReporterSupport)[388] <Notice>: cr_update: <private>
Sep 10 10:10:47 PI-iPad-04 ReportCrash(CrashReporterSupport)[388] <Notice>: cr_update: <private>
Sep 10 10:10:47 PI-iPad-04 ReportCrash[388] <Notice>: __crash_info: [<private>] '(null)'
Sep 10 10:10:47 PI-iPad-04 ReportCrash[388] <Notice>: __crash_info: [<private>] '<private>'
Sep 10 10:10:48 PI-iPad-04 ReportCrash[388] <Notice>: __crash_info: [<private>] '(null)'
```
Does this provide more info as to the possible cause?

**Comment by tomblench** [comment] 2017-09-11 07:51
Looks like an assertion failed somewhere in our `TDMultiStreamWriter` code. You can find out exactly where by searching for "ASSERTION FAILED" in the system log on the device.

**Comment by paulJordaan** [comment] 2017-09-12 06:00
Okay, the assertion failure looks like it happens inside `[TDMultiStreamWriter writeToOutput]`. I've confirmed that this is actually only happening on a push replication. Could this by any change be related to the following issue https://github.com/couchbase/couchbase-lite-ios/issues/665 ?

```
Sep 12 06:48:21 PI-iPad-04 D-Fect[513] <Notice>: TDPusher [https://3e0fa932-2655-4622-8d37-f7bc66541891-bluemix.cloudant.com/dfect_production]: POST _revs_diff
Sep 12 06:48:21 PI-iPad-04 D-Fect[513] <Notice>: TDRemoteJSONRequest[POST https://3e0fa932-2655-4622-8d37-f7bc66541891-bluemix.cloudant.com/dfect_production/_revs_diff]: Starting...
Sep 12 06:48:21 PI-iPad-04 nsurlsessiond[112] <Notice>: Current discretionary status for <private> is non-discretionary
Sep 12 06:48:21 PI-iPad-04 nsurlsessiond[112] <Notice>: Enqueueing Task 34 with UUID <private> for client <private>, session <private>
Sep 12 06:48:21 PI-iPad-04 nsurlsessiond[112] <Notice>: Task 34 requesting URL <private>
Sep 12 06:48:21 PI-iPad-04 D-Fect[513] <Notice>: Waiting on asyncTaskMonitor
Sep 12 06:48:21 PI-iPad-04 D-Fect[513] <Notice>: Wait completed
Sep 12 06:48:21 PI-iPad-04 nsurlsessiond[112] <Notice>: Client <private> resume for task 34
Sep 12 06:48:21 PI-iPad-04 D-Fect[513] <Notice>: *** TDPusher [https://3e0fa932-2655-4622-8d37-f7bc66541891-bluemix.cloudant.com/dfect_production]: END processInbox (lastSequence=72244)
Sep 12 06:48:21 PI-iPad-04 nsurlsessiond(CFNetwork)[112] <Notice>: TIC TCP [0x1074bd150] working for task <private>
Sep 12 06:48:21 PI-iPad-04 nsurlsessiond(CFNetwork)[112] <Notice>: TIC TCP [0x1074bd150] working for task <private>
Sep 12 06:48:21 PI-iPad-04 D-Fect[513] <Notice>: <TDMultipartWriter: 0x1746f5180>: Received event 0x1
Sep 12 06:48:21 PI-iPad-04 nsurlsessiond[112] <Notice>: Task 34 for client <private> has a connection
Sep 12 06:48:21 PI-iPad-04 D-Fect[513] <Notice>: <TDMultipartWriter: 0x1746f5180>:   Refilling buffer
Sep 12 06:48:21 PI-iPad-04 nsurlsessiond(CFNetwork)[112] <Notice>: TIC TCP [0x1074bd150] working for task <private>
Sep 12 06:48:21 PI-iPad-04 nsurlsessiond(CFNetwork)[112] <Notice>: TIC TCP [0x1074bd150] working for task <private>
Sep 12 06:48:21 PI-iPad-04 D-Fect[513] <Notice>: <TDMultipartWriter: 0x1746f5180>:     read 98 bytes from <__NSCFInputStream: 0x17430df50>
Sep 12 06:48:21 PI-iPad-04 D-Fect[513] <Notice>: <TDMultipartWriter: 0x1746f5180>:     read 0 bytes from <__NSCFInputStream: 0x17430df50>
Sep 12 06:48:21 PI-iPad-04 D-Fect[513] <Notice>: <TDMultipartWriter: 0x1746f5180>:     read 1262 bytes from <__NSCFInputStream: 0x17430df50>
Sep 12 06:48:21 PI-iPad-04 D-Fect[513] <Notice>: <TDMultipartWriter: 0x1746f5180>:     read 0 bytes from <__NSCFInputStream: 0x17430df50>
Sep 12 06:48:21 PI-iPad-04 D-Fect[513] <Notice>: <TDMultipartWriter: 0x1746f5180>:     read 150 bytes from <__NSCFInputStream: 0x170310500>
Sep 12 06:48:21 PI-iPad-04 D-Fect[513] <Notice>: <TDMultipartWriter: 0x1746f5180>:     read 0 bytes from <__NSCFInputStream: 0x170310500>
Sep 12 06:48:21 PI-iPad-04 D-Fect[513] <Notice>: <TDMultipartWriter: 0x1746f5180>:     read -1 bytes from <__NSCFInputStream: 0x170307b30>
Sep 12 06:48:21 PI-iPad-04 D-Fect[513] <Notice>: <TDMultipartWriter: 0x1746f5180>: Error on <__NSCFInputStream: 0x170307b30>: (null)
Sep 12 06:48:21 PI-iPad-04 D-Fect[513] <Notice>: <TDMultipartWriter: 0x1746f5180>:     at end of input, can't refill
Sep 12 06:48:21 PI-iPad-04 D-Fect[513] <Notice>: <TDMultipartWriter: 0x1746f5180>: Received event 0x4
Sep 12 06:48:21 PI-iPad-04 D-Fect[513] <Notice>: *** ASSERTION FAILED: _bufferLength > 0
Sep 12 06:48:21 PI-iPad-04 D-Fect(Foundation)[513] <Notice>: *** Assertion failure in -[TDMultipartWriter writeToOutput], /Users/pauljordaan/Projects/ios/D-Fect-rollback/d-fect-ios/Pods/CDTDatastore/CDTDatastore/touchdb/TDMultiStreamWriter.m:226
Sep 12 06:48:21 PI-iPad-04 nsurlsessiond(CFNetwork)[112] <Notice>: TIC TCP Conn Cancel [489:0x107490ce0]
Sep 12 06:48:21 PI-iPad-04 nsurlsessiond(CFNetwork)[112] <Notice>: TIC TCP [0x107490ce0] completing activity 0x1074ae7f0
Sep 12 06:48:21 PI-iPad-04 DuetHeuristic-BM(DuetActivitySchedulerDaemon)[110] <Notice>: COMPLETED <private>!
Sep 12 06:48:21 PI-iPad-04 DuetHeuristic-BM(DuetActivitySchedulerDaemon)[110] <Notice>: Stop network path monitoring for '<private>'
Sep 12 06:48:21 PI-iPad-04 DuetHeuristic-BM(DuetActivitySchedulerDaemon)[110] <Notice>: NO LONGER RUNNING <private> ...Tasks running in group [<private>] are 2!
Sep 12 06:48:21 PI-iPad-04 DuetHeuristic-BM(DuetActivitySchedulerDaemon)[110] <Notice>: <private>:[
<private> ] sumScores:23.678571, denominator:31.700000, FinalDecision: Can Proceed FinalScore: 0.746958}
Sep 12 06:48:21 PI-iPad-04 DuetHeuristic-BM(DuetActivitySchedulerDaemon)[110] <Notice>: '<private>' DecisionToRun:1 (Bypasses Predictions)
Sep 12 06:48:21 PI-iPad-04 DuetHeuristic-BM(DuetActivitySchedulerDaemon)[110] <Notice>: With <private> ...Tasks running in group <private> are 3!
Sep 12 06:48:21 PI-iPad-04 DuetHeuristic-BM(DuetActivitySchedulerDaemon)[110] <Notice>: Stop network path monitoring for '<private>'
Sep 12 06:48:21 PI-iPad-04 DuetHeuristic-BM(DuetActivitySchedulerDaemon)[110] <Notice>: Running activities : <private>
Sep 12 06:48:21 PI-iPad-04 nsurlsessiond(DuetActivityScheduler)[112] <Notice>: STARTING: <private>
Sep 12 06:48:21 PI-iPad-04 nsurlsessiond(CFNetwork)[112] <Notice>: TIC [0x1074985c0]: activity 0x1074f0320 start handler called
Sep 12 06:48:21 PI-iPad-04 nsurlsessiond(CFNetwork)[112] <Notice>: TIC TCP Conn Start [491:0x1074985c0]
Sep 12 06:48:21 PI-iPad-04 nsurlsessiond[112] <Notice>: Task 34 for client <private> received response, status code: 200
Sep 12 06:48:21 PI-iPad-04 nsurlsessiond(CFNetwork)[112] <Notice>: TIC TCP Conn Event [491:0x1074985c0]: 1 Err(0)
Sep 12 06:48:21 PI-iPad-04 nsurlsessiond(CFNetwork)[112] <Notice>: TIC TCP Conn Connected [491:0x1074985c0]: Err(0)
Sep 12 06:48:21 PI-iPad-04 nsurlsessiond(CFNetwork)[112] <Notice>: TIC Enabling TLS [491:0x1074985c0]
Sep 12 06:48:21 PI-iPad-04 D-Fect(CoreFoundation)[513] <Notice>: *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '_bufferLength > 0'
*** First throw call stack:
(0x186462fe0 0x184ec4538 0x186462eb4 0x186efb760 0x10010177c 0x1000f0ee4 0x1000f1078 0x1863ae01c 0x1863adf28 0x18641142c 0x186410d9c 0x18640e9a8 0x18633eda4 0x186e59db4 0x1000fb4fc 0x186f57318 0x18552568c 0x18552559c 0x185522cb4)
Sep 12 06:48:21 PI-iPad-04 nsurlsessiond[112] <Notice>: Task 34 for client <private> completed successfully
Sep 12 06:48:21 PI-iPad-04 D-Fect[513] <Notice>: Signalling asyncTaskMonitor
```

**Comment by tomblench** [comment] 2017-09-12 13:52
@paulJordaan the latest stack trace appears to be on a **push** replication so this might be a different issue to the one you reported. Are you doing push and pull replications? The couchbase lite issue may be relevant since this part of the codebase hasn't diverged much from theirs. 

However, I suspect that even if we fix this bug it would be masking another problem which is that the uploading of attachments is failing. Do you have very large attachments you need to upload and download? If so, you might encounter problems, especially in a mobile/unreliable network context. This is because if an attachment upload or download fails we can't resume where it failed - the whole payload has to be sent again.

If you have very large attachments we can discuss other ways of storing them.

**Comment by paulJordaan** [comment] 2017-09-12 21:02
@tomblench correct, I made a mistake in reporting the issue as a problem with a pull replication. The issue is actually occurring during push replication as mentioned in my previous comment. 

My attachments have an average size of around 250kb so I do not think large attachments are the cause.

**Comment by tomblench** [comment] 2017-09-13 06:47
OK those aren't very big attachments.

We're having a difficult time reproducing this. Is there a certain situation when this always occurs or is this an intermittent issue?

**Comment by paulJordaan** [comment] 2017-09-13 08:05
I have a few devices reporting this issue. Once it occurs that device is not able to do any push replications going ahead.

**Comment by tomblench** [comment] 2017-09-13 09:08
@paulJordaan ok thanks for the clarification. For me the most important lines are:
```

Sep 12 06:48:21 PI-iPad-04 D-Fect[513] <Notice>: <TDMultipartWriter: 0x1746f5180>:     read -1 bytes from <__NSCFInputStream: 0x170307b30>
Sep 12 06:48:21 PI-iPad-04 D-Fect[513] <Notice>: <TDMultipartWriter: 0x1746f5180>: Error on <__NSCFInputStream: 0x170307b30>: (null)
```

This looks like it is trying to read the attachment from local storage/disk and is failing. I think the 3 successful reads which precede it are the mime multipart/related header, the json body, and the boundary preceding the attachment.

The strange thing is that `[NSInputStream read]` will return -1 if there is an error, the docs say `-1 means that the operation failed; more information about the error can be obtained with 
streamError`. But you can see that the error we are fetching from `streamError` is `null`.

You can contrast this with a situation where I have contrived to make the local attachment unreadable by changing the permissions in it:

```
TDMultipartWriter: 0x10081bde0>: Opened input=0x10070a710, output=0x1007175d0
2017-09-13 09:51:46:662 xctest[88904:9677964] <TDMultipartWriter: 0x10081bde0>: Received event 0x1
2017-09-13 09:51:46:662 xctest[88904:9677964] <TDMultipartWriter: 0x10081bde0>:   Refilling buffer
2017-09-13 09:51:46:662 xctest[88904:9677964] <TDMultipartWriter: 0x10081bde0>:     read 97 bytes from <__NSCFInputStream: 0x100734cc0>
2017-09-13 09:51:46:662 xctest[88904:9677964] <TDMultipartWriter: 0x10081bde0>:     read 0 bytes from <__NSCFInputStream: 0x100734cc0>
2017-09-13 09:51:46:662 xctest[88904:9677964] <TDMultipartWriter: 0x10081bde0>:     read 398 bytes from <__NSCFInputStream: 0x100b4fd60>
2017-09-13 09:51:46:662 xctest[88904:9677964] <TDMultipartWriter: 0x10081bde0>:     read 0 bytes from <__NSCFInputStream: 0x100b4fd60>
2017-09-13 09:51:46:662 xctest[88904:9677964] <TDMultipartWriter: 0x10081bde0>:     read 132 bytes from <__NSCFInputStream: 0x100982720>
2017-09-13 09:51:46:663 xctest[88904:9677964] <TDMultipartWriter: 0x10081bde0>:     read 0 bytes from <__NSCFInputStream: 0x100982720>
2017-09-13 09:51:46:663 xctest[88904:9677964] <TDMultipartWriter: 0x10081bde0>:     read -1 bytes from <__NSCFInputStream: 0x10086c0f0>
2017-09-13 09:51:46:663 xctest[88904:9677964] <TDMultipartWriter: 0x10081bde0>: Error on <__NSCFInputStream: 0x10086c0f0>: Error Domain=NSPOSIXErrorDomain Code=13 "Permission denied" UserInfo={_kCFStreamErrorCodeKey=13, _kCFStreamErrorDomainKey=1}
2017-09-13 09:51:46:664 xctest[88904:9677964] <TDMultipartWriter: 0x10081bde0>:     at end of input, can't refill
2017-09-13 09:51:46:664 xctest[88904:9677964] <TDMultipartWriter: 0x10081bde0>: Received event 0x4
2017-09-13 09:51:46:664 xctest[88904:9677964] <TDMultipartWriter: 0x10081bde0>:   Input isn't open; waiting...
2017-09-13 09:51:46.672004+0100 xctest[88904:9676290]  -> CDTReplicatorStateStarted
2017-09-13 09:51:46:765 xctest[88904:9677964] <TDMultipartWriter: 0x10081bde0>: Received event 0x4
2017-09-13 09:51:46.766477+0100 xctest[88904:9677964] *** ASSERTION FAILED: _bufferLength > 0
2017-09-13 09:51:46.766556+0100 xctest[88904:9677964] *** Assertion failure in -[TDMultipartWriter writeToOutput], /Users/tomblench/cloudant_dev/CDTDatastore/CDTDatastore/touchdb/TDMultiStreamWriter.m:226
2017-09-13 09:51:46.767968+0100 xctest[88904:9677964] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '_bufferLength > 0'
```
Note that we get an error in this case `Error on <__NSCFInputStream: 0x10086c0f0>: Error Domain=NSPOSIXErrorDomain Code=13 "Permission denied" UserInfo={_kCFStreamErrorCodeKey=13, _kCFStreamErrorDomainKey=1}`

**Comment by paulJordaan** [comment] 2017-09-14 05:03
@tomblench, I took a stab in the dark and implemented the patch from couchbase-lite (couchbase/couchbase-lite-ios#665). Was then able to complete my replication without issue.

I wish I  could have identified exactly why the issue was occurring but I'm not familiar enough with the codebase and internal workings of this library.

My suggestion is to merge in the patch from couchbase. When I have the time I will submit a pull request of my version if you do not have the time. I just need to clean up the code, check for comment etc. Thanks for the help and great library.

**Comment by tomblench** [comment] 2017-09-14 08:54
@paulJordaan thanks for tracking this down, great work. Unfortunately we might have an issue around the intellectual property of the patch (yes, even for a small patch like this) - see https://github.com/cloudant/CDTDatastore/blob/master/CONTRIBUTING.md. And because the patch isn't yours, you can't sign off agreement with the "Developer Certificate of Origin"

I need to discuss with my colleagues the best way to proceed with this but obviously you should carry on applying the patch to your software in the meantime.

**Comment by tomblench** [comment] 2017-10-19 14:02
@paulJordaan sorry for the delay, are you still happy to submit a pull request? We would be grateful for your contribution as long as you are happy to assert your compliance to the [DCO](https://github.com/cloudant/CDTDatastore/blob/master/DCO1.1.txt). We think that you are covered by part (b) because the patch is under the same licence as this project.

**Comment by ricellis** [comment] 2022-01-27 13:42
This library is now end-of-life and this issue won't be fixed.
This issue has been [tagged `EOL`](https://github.com/cloudant/CDTDatastore/issues?q=is%3Aissue+label%3AEOL) in case any forks want to import it.

**Closed by ricellis** 2022-01-27 13:42 UTC
Labels: bug, EOL
