### ISSUE TITLE
iOS Application crashes during sync

### ISSUE THREAD

**Issue by AjayHegdeK** [cloudant/CDTDatastore#439] opened 2018-07-19 11:42 UTC
## Bug Description
Application crashes giving the following error mentioned below.

Fatal error: Failed to initialize datastore: Error Domain=CDTDatastoreErrorDomain Code=400 "Couldn't create database." UserInfo={NSLocalizedRecoverySuggestion=Wrong key?, NSLocalizedDescription=Couldn't create database., NSLocalizedFailureReason=Wrong key?}: file /Users/path/DataStore/DataStoreManager.swift

I found in google that similar issue was raised long back,
Link of the issue:  https://github.com/cloudant/CDTDatastore/issues/363
 
can you suggest us how to solve this issue.

Steps to reproduce:
Syncing data during pulll replication app crashes throwing the above mentioned error.

## Environment details
Using Swift 4.0 for development
- Version(s) that are affected by this issue.
    > IOS 11.3

**Comment by emlaver** [comment] 2018-07-19 14:20
@AjayHegdeK please provide sample code that reproduces this issue.

**Comment by AjayHegdeK** [comment] 2018-07-20 05:42
class func initDatastore(name: String) -> CDTDatastore? {
        if RegEx.evaluate(pattern: databaseNamePattern, string: name) != true {
            Log.error("Datastore naming format is incorrect: \(name)")
            return nil
        }
        
        guard let datastoreManager = shared else {
            return nil
        }
        
        // Create datastore
        var datastore: CDTDatastore?
        do {
            try serialQueue.sync {
                datastore = try datastoreManager.datastoreNamed(name) // application crashes here 
            }
        } catch {
            Log.severe("Failed to initialize datastore: \(error)")
            fatalError("Failed to initialize datastore: \(error)")
        }
        // Create Index
        indexDatastore(datastore: datastore)
        
        return datastore
    }

**Comment by emlaver** [comment] 2018-07-20 14:59
@AjayHegdeK We could not replicate the issue with the code sample you've sent.  Can you please provide the full code or an Xcode project which reproduces this issue?
Also, which version of `CDTDatastore` library are you using?

If you can provide additional logging for this scenario in your app that would be helpful.

**Comment by emlaver** [comment] 2018-08-02 14:09
Closing as stale, please reopen if you require further assistance.

**Comment by navaneet** [comment] 2018-09-04 06:14
@emlaver We are again getting this issue, it's extremely hard to reproduce and we have been unable to reproduce the issue by ourselves however it shows up in our app's crashlytics logs.

`Fatal error: Failed to initialize datastore: Error Domain=CDTDatastoreErrorDomain Code=400 "Couldn't create database." UserInfo={NSLocalizedRecoverySuggestion=Wrong key?, NSLocalizedDescription=Couldn't create database., NSLocalizedFailureReason=Wrong key?}: file /Users/nav/Codes/connected-crew-ios/MVC/DataStore/DataStoreManager.swift, line 67`

The code that fails is this part which initialises the datastore

```
     do {
                datastore = try datastoreManager.datastoreNamed(name)
          } catch {
            Log.severe("Failed to initialize datastore: \(error)")
            fatalError("Failed to initialize datastore: \(error)")
        }
```
Do you guys have any updates on this issue. Also by the way we are using the latest version of CDTDatastore library 2.1.0

**Comment by smithsz** [comment] 2018-09-04 10:44
We have been unsuccessful in reproducing this issue with the details you've provided.
Are you able to provide a full reproduction case (including details about the iOS devices you're running)?
It's very difficult for us to investigate further without being able to trigger this error condition.
Thanks.

**Comment by navaneet** [comment] 2018-09-04 15:06
@smithsz Thanks for the quick reply, much appreciated :) , like I mentioned before, we ourselves haven't been able to reproduce this issue however it does happen on client tablets and phones as evidenced from the crashlytics logs.

We have seen this issue happening in iOS 11.4.1 and it seems to happen on both iPhones and iPads. At least that's what we get in terms of crash analytics from crashlytics. Does that help?

The following line basically returns nil 

`datastore = try datastoreManager.datastoreNamed(name)`

Can you help us pinpoint the source of probable conditions under which the datastoreNamed method will return nil?

Also we have a doubt that it might be related to concurrency issue as well. Is the datastoreNamed method thread safe?

**Comment by smithsz** [comment] 2018-09-04 15:40
Yeah, this method is thread safe. It's in a synchronized block.

That `Code=400. "Couldn't create database" ...` error is likely masking the true problem. It gets set [here](https://github.com/cloudant/CDTDatastore/blob/master/CDTDatastore/CDTDatastoreManager.m#L77) when `initWithManager` returns `nil`.

Does crashlytics provide a full device log? I'm wondering if there's anything else useful in there that could explain the `nil` return.

**Comment by navaneet** [comment] 2018-09-04 15:59
I agree, just wondering under what conditions it might return nil 🤔

As for crashlytics it doesn't provide much details, the crash happens within our indexing code when the datastore is returned as nil. 

For example this recent log that I have attached will mention that it crashes in indexDatastore method which is a method we have written for indexing however, the crash happens even before it can reach any indexing related code as the datastore itself is returned as nil and crash happens on any  access of the datastore methods.

`DataStoreManager.indexDatastore(datastore : CDTDatastore?) -> () (DataStoreManager.swift:76)`

[issue_8_crash_77020b31927846b3972894b3ebfb0cd7_DNE_0_v2.txt](https://github.com/cloudant/CDTDatastore/files/2349342/issue_8_crash_77020b31927846b3972894b3ebfb0cd7_DNE_0_v2.txt)

**Comment by navaneet** [comment] 2018-09-04 16:16
@smithsz By the way what does the error reason mean ?

` errorReason = NSLocalizedString(@"Wrong key?", nil);
`
Is it related to encryption key? I can confirm you that we are not using any encryption key provider explicitly don't know if the library internally uses one. Are we missing something in terms of cocoapods configuration?

The issue mentioned here seems similar https://github.com/cloudant/CDTDatastore/issues/363

**Comment by smithsz** [comment] 2018-09-05 09:57
It means it's failed to open the datastore with the specified encryption key provider. But since you don't specify one you get the default `CDTEncryptionKeyNilProvider` anyway.

**Comment by smithsz** [comment] 2018-09-05 10:44
If you turn on encryption (`ENCRYPT_DATABASE=1`) for the local datastore you have to use the pod `CDTDatastore/SQLCipher` to bring in `FMDB/SQLCipher` instead of `FMDB`. That said, if you weren't using encryption before I would advise against enabling it in the middle of this issue as it will just introduce more moving parts that makes this harder to debug.

Your code shows that you catch the fatal error from datastore initialization and then proceed to call `indexDatastore` anyway, which is where the crash happens. I would suggest you can at least stop the crash occurring by not proceeding after logging the fatal exception, but by exiting gracefully or attempting to create the datastore again. Trying to call functions and return a reference to the datastore (which is `nil`) after receiving a fatal error is not going to work.

**Comment by navaneet** [comment] 2018-09-05 11:13
@smithsz Thanks for the suggestion, and yes that's what I have done for the upcoming build, I just put nil checks using if let statements wherever the datastore is accessed from however, I do understand that this is not a permanent fix and eventually will cause some hard to debug issues.

By the we are using the latest xcode version 9.4.1 and swift version 4.1. I am not sure if the issue is caused due to the access of some macros internally by the library which are not adaptable to the swift environment. Maybe you guys can clarify on that, I don't know much about the internals or the inner working of the library.

**Comment by navaneet** [comment] 2018-09-06 06:03
Hi, this is the latest crash log, one that I have also shared earlier in the thread

[issue_8_crash_77020b31927846b3972894b3ebfb0cd7_DNE_0_v2.txt](https://github.com/cloudant/CDTDatastore/files/2355614/issue_8_crash_77020b31927846b3972894b3ebfb0cd7_DNE_0_v2.txt)

However, crashlytics just captures the stack trace of any crash as they happen and not the steps taken to reach the point of crash. For example it might tells us that indexDatastore is crashing because nil value was encountered at certain file and line number but, what it doesn't tell us is, what set the value to nil in the first place.

If we have to log such conditions wherein datastore is about to return nil then we will need to explicitly log those inside the library source code.

For example: 

If this code inside the library is failing for some reason 

```
   if (db) {
            datastore = [[CDTDatastore alloc] initWithManager:self database:db encryptionKeyProvider:provider];
            
            if (!datastore) {
                errorReason = NSLocalizedString(@"Wrong key?", nil);
            }
```

which is located here https://github.com/cloudant/CDTDatastore/blob/master/CDTDatastore/CDTDatastoreManager.m#L77

then we need to log the error reason in a more verbose manner. Can you guys please expand the error reason to contain maybe info on which db it fails for and the encryptionKeyProvider etc.

Then we can log those errorReasons explicitly from our codebase to crashlytics and send you those reports for further verification. Does that help?

Also, following is the error Reason we currently log which comes from the library  

`Fatal error: Failed to initialize datastore: Error Domain=CDTDatastoreErrorDomain Code=400 "Couldn't create database." UserInfo={NSLocalizedRecoverySuggestion=Wrong key?, NSLocalizedDescription=Couldn't create database., NSLocalizedFailureReason=Wrong key?}: file /Users/nav/Codes/connected-crew-ios/MVC/DataStore/DataStoreManager.swift, line 67`

**Comment by ricellis** [comment] 2018-09-06 09:46
Yes, I have already looked at the crash log and as both you and our team have said it doesn't help much in this circumstance.

We don't need to add any additional debug at this point in time - there are _already_ log messages in the code that would give us more information - you just need to figure out how your app can collect them from the crash. I don't think you need to explicitly add logging statements you need to connect our existing logging to your crash collection - i.e. I think you'll want to connect the CocoaLumberjack logging to crashlytics - a quick search suggests that some people have already solved this problem [[1]](https://github.com/TechSmith/CrashlyticsLumberjack) [[2]](https://gist.github.com/alexruperez/e3ee37d71d568ceb975b4edcf4167ccd). You may want to investigate those or write your own handler then you ought to be able to use `DDLog.add` to connect a handler for the crashlytics CLS logger.

Please review the [logging documentation](https://github.com/cloudant/CDTDatastore/blob/master/doc/logging.md). The minimum logging you should try to collect for this issue is `DDLogLevelWarning` for the `CDTDATASTORE_LOG_CONTEXT`.

**Comment by navaneet** [comment] 2018-09-06 10:55
@ricellis K thanks for the pointers, we will try them out.

**Comment by vladmoh** [comment] 2018-09-06 15:42
Hello,

one way to reproduce the issue described here is to delete keychain entries.
Cloudant Sync stores values in iOS keychain and if these values are wiped/overwritten or corrupted, the library will not be able to open encrypted database file.
You can test/preproduce the issue by deleting/overwriting keychain programmatically from within the mobile app or by using tools like Objection:
https://github.com/sensepost/objection

Once keychain is lost -  there is no way to recover AES-256 encrypted data, you will have to delete and recreate the database file. To recover, we can either delete and re-install the application or programmatically delete encrypted database file from within the code.

**Comment by ricellis** [comment] 2018-09-06 15:57
@vladmoh thanks I think that is probably a valid way to reproduce #363, but in this case the database is not encrypted so I believe the root cause to be different even though the error message is the same. The error message is misleading here because it mentions a key, but the message is the [same in all circumstances when the database is not opened](https://github.com/cloudant/CDTDatastore/blob/master/CDTDatastore/CDTDatastoreManager.m#L77).

**Comment by vladmoh** [comment] 2018-09-06 16:13
@ricellis I see now, thanks! another issue we had that was maybe similar is when the database was initially created as encrypted and attempted to open as not encrypted.
Maybe @AjayHegdeK  or @navaneet  could confirm whether the database was ever encrypted?

**Comment by navaneet** [comment] 2018-09-06 16:26
I can confirm that we don't explicitly encrypt the database however I don't know if it's implicitly done by the library or something. Also the random nature of this crash makes it very hard to reproduce.

I see this issue mostly when I release new builds, weird issue indeed . By the way we release our builds through testflight and that's when I see this issue in crashlytics. In normal development mode the app doesn't crash with this error message.

**Comment by ricellis** [comment] 2018-10-09 14:11
Closing for now, please re-open if you manage to get the logs from a crash.

**Closed by ricellis** 2018-10-09 14:11 UTC

**Comment by alv-ti8m** [comment] 2019-10-08 06:39
Having the same issue. CDTDatastore created without encryption. If I create the datastore in a normal background everything works. The issue raises when iOS kills my app and later start a background fetch activity. In this case, when trying to create the datastore, it fails with the error:
`Failed to initialize CouchDB: Error Domain=CDTDatastoreErrorDomain Code=400 "Couldn't create database." UserInfo={NSLocalizedRecoverySuggestion=Wrong key?, NSLocalizedDescription=Couldn't create database., NSLocalizedFailureReason=Wrong key?}`

I enabled the CocoaLumberjack logs, but they don't really help me:
```
2019/10/08 07:26:08:777  opening new CDTDatastore yondermind-test_couch-db
2019/10/08 07:26:08:778  Open /var/mobile/Containers/Data/Application/0A8175A0-B0BE-445B-A35B-A2A8DA2109A6/Documents/yondermind-test_store/yondermind-test_couch-db.touchdb (flags=200006)
2019/10/08 07:26:08:779  -dealloc CDTDatastore <CDTDatastore: 0x283ec6100>
2019/10/08 07:26:08:780  -dealloc CDTDatastoreManager <CDTDatastoreManager: 0x2830da960>
2019/10/08 07:26:08:780  DEALLOC <TD_DatabaseManager: 0x2830da940>
2019/10/08 07:26:08:780  CLOSING <TD_DatabaseManager: 0x2830da940> ...
2019/10/08 07:26:08:780  CLOSED <TD_DatabaseManager: 0x2830da940>
2019/10/08 07:26:08:780  -dealloc TD_Database TD_Database[/var/mobile/Containers/Data/Application/0A8175A0-B0BE-445B-A35B-A2A8DA2109A6/Documents/yondermind-test_store/yondermind-test_couch-db.touchdb]
```

Any idea? Do you need more information?

**Comment by vladmoh** [comment] 2019-10-08 14:10
@alv-ti8m i would check two things:
1. whether the key created by CDTDatastore is still in your keychain.
2. whether the database was actually encrypted.
If your either your application or one of the included libraries indiscriminately delete all the keys - all data is lost. You can use https://github.com/sensepost/objection framework to monitory the keychain content or any other tools you can find. You can also use objection framework to download your database from iOS device and to to open and explore SQLite locally to see whether it was actually encrypted. If you can reproduce the problem in iOS simulator - even easier as you can simply find SQLite db file on your local hard drive.

**Comment by alv-ti8m** [comment] 2019-10-09 12:08
Hi @vladmoh, as I wrote, I'm not encrypting the database. I'm using iTunes for getting the document folder from where I can get the database and I can confirm you that it's not encrypted. I can normally open with a db browser without providing any key. 
This issue looks related only to the background fetch task. If I start the app normally, couchdb is successfully created and no crash are generated. Instead, if the app is run from a background fetch task, the couchdb creation failed, without actually telling me why. I wrote the logs that I got and I think that they are not helpful.

I specify that this crash happens only if the app is run in background after it was killed by the system. I always make a check on couchdb for knowing if the instance is available or not, and this crash happens only when it's not and the app needs to create it during the background fetch task.

If I perform a background fetch from Xcode this works, even if I let the app create couchdb during the execution this task.

**Comment by vladmoh** [comment] 2019-10-14 22:14
@alv-ti8m hm... i missed the "not encrypted" part and i guess i was partially thrown of by "Wrong key?" error. I get a feeling CDTDatastore might still be storing something in the keychain even for non-encrypted data? Not sure why but should be easy to check keychain once DB is created.

**Comment by alv-ti8m** [comment] 2019-10-15 06:32
Hi @vladmoh I had a look on my Keychain and it is completely empty. I don't store anything on it, and looking on the result also CDT is not. 
Any idea on what it causing my issue?

**Comment by vladmoh** [comment] 2019-10-15 15:41
@alv-ti8m Interesting.. Are you able to debug the code? The only place i see "Wrong Key?" being thrown is in CDTDatastoreManager.m:

https://github.com/cloudant/CDTDatastore/blob/0ccbe1a887f966cfc13a13dfd9a0b77a01b6cb3a/CDTDatastore/CDTDatastoreManager.m

if you set a debug point at line 74 and check whether the database file actually exists and whether any provider is being passed into initWithManager - it could shed some light into whats going on here. Also you may want to step into the "initWithManager" method to see what it's trying to do.

        NSString *errorReason = nil;
        TD_Database *db = [self.manager databaseNamed:name];
        if (db) {
            datastore = [[CDTDatastore alloc] initWithManager:self database:db encryptionKeyProvider:provider];
            
            if (!datastore) {
                errorReason = NSLocalizedString(@"Wrong key?", nil);
            }
        } else {
            errorReason = NSLocalizedString(@"Invalid name?", nil);
        }

**Comment by alv-ti8m** [comment] 2019-10-16 07:07
@vladmoh it's actually impossible for me to debug this code, since this crash only happen on real device when performing background fetch task. Also, running a background fetch task with Xcode does not produce this crash. What I will do is to replace the initWithManager call and I will directly call the constructor of the CDTDatastore. In this way I should have more control and also I can debug or at least put more logs without changing the library. I'll let you know what I will find
