### ISSUE TITLE
Getting an FMDatabaseQueue dealloc issue while trying to delete datastore

### ISSUE THREAD

**Issue by navaneet** [cloudant/CDTDatastore#450] opened 2018-11-14 12:47 UTC
## Bug Description

We are getting a random FMDatabaseQueue dealloc issue while trying to delete a datastore.  Not sure if it's related to the following issue

https://github.com/ccgus/fmdb/issues/659

### 1. Steps to reproduce and the simplest code sample possible to demonstrate the issue

Following function creating the exception:

```
    /// Deletes a datastore from the device
    ///
    /// - Parameter name: name of the datastore to delete
    public class func deleteDatastore (_ name: String) {
        do {
            try shared?.deleteDatastoreNamed(name)
            DataStoreNotification.deleteDataStoreNotify()
            Log.info("deleted db named: \(name)")
        } catch {
            Log.error("datastore doesn't exist \(error)")
        }
    }
```

### 2. What you expected to happen

Not to crash

### 3. What actually happened

It crashed

<img width="875" alt="screenshot 2018-11-14 at 6 10 36 pm" src="https://user-images.githubusercontent.com/2356187/48483166-b78bb880-e838-11e8-9a66-fbbe531c6a99.png">

Attaching crash log as well

[2018-11-11_22-03-57.2043_+0100-31daa74dd4da0a822c24d3847453e2dbe6336985 2.crash.zip](https://github.com/cloudant/CDTDatastore/files/2580758/2018-11-11_22-03-57.2043_%2B0100-31daa74dd4da0a822c24d3847453e2dbe6336985.2.crash.zip)

## Environment details
- Version(s) that are affected by this issue.
    > 2.1.1
- iOS version
    > 12.0.1

**Comment by navaneet** [comment] 2018-11-14 15:29
@tomblench Thanks for the quick response, I have been trying to reproduce this issue however haven't been able to reproduce it in development, it's occurring only in production.

Do you think it's related to https://github.com/cloudant/CDTDatastore/issues/426 or is it a separate issue?

**Comment by tomblench** [comment] 2018-11-14 15:36
Yes they appear related because the crash happens in `-[FMDatabaseQueue dealloc]` in both instances.

**Comment by navaneet** [comment] 2018-11-14 15:48
Is it feasible for the issue described in https://github.com/cloudant/CDTDatastore/issues/426 to be fixed within the library itself?

To be honest, we have tried on our own many times with multiple permutation combinations of autoreleaspool and even some other memory management paradigms as well, however nothing seems to work currently with what we tried with our codebase to fix this specific issue. 

We are out of ideas on this one, hence requesting you to please take a look at this issue.

**Comment by tomblench** [comment] 2018-11-14 15:52
You may not have seen my edited comment.

`and the issue is still easily reproducible` - if so please provide us with a self-contained block of code we can run to easily reproduce the bug and we will investigate. The code provided in the original "Steps to reproduce" contains only one API call to our library and is not a self-contained block of code which will trigger the bug you are observing.

I'm sorry about that but we can't investigate something we can't see ourselves.

**Comment by navaneet** [comment] 2018-11-14 16:34
I understand, let me share a quick sample

The following sample code illustrates the issue mentioned in https://github.com/cloudant/CDTDatastore/issues/426

[DataStore Sample.zip](https://github.com/cloudant/CDTDatastore/files/2581563/DataStore.Sample.zip)

As for issue https://github.com/cloudant/CDTDatastore/issues/450 I had some doubts regarding the culprit being a replication job on the same datastore which is being deleted, and it seems there actually is an issue the CDTReplicator leaking, just not sure yet if they are related.

Check my below screenshots from the "Leaks" instrumentation I ran on our main codebase just now and the leaks I noticed with a simple replication job itself that too on the first landing page of our app, didn't even had to go beyond the login page.

Do you think it's related? We haven't done anything fancy with the replicator, not sure why it's leaking

<img width="1278" alt="screenshot 2018-11-14 at 9 55 13 pm" src="https://user-images.githubusercontent.com/2356187/48496621-71dee800-e858-11e8-9603-14b1398973fa.png">
<img width="1279" alt="screenshot 2018-11-14 at 9 56 07 pm" src="https://user-images.githubusercontent.com/2356187/48496624-72777e80-e858-11e8-88ae-c6ecdbd36fd1.png">

Code for the replicator:

```
           do {
                    let replicator: CDTReplicator = try factory.oneWay(replication)
                    replicator.delegate = self
                    replicator.sessionConfigDelegate = self
                    try replicator.start(withTaskGroup: dispatchGroup)
                    completionHandler?(.started)
                    Log.debug("Sync Started: \(replicator)")
                } catch {
                    completionHandler?(.errored)
                    Log.error("Error initializing \(direction) sync: \(error)")
                    return
                }
```

**Comment by ricellis** [comment] 2018-12-10 16:38
The reference to `retainedSelf` is intentional and used to allow the `CDTReplicator` to be ["fire and forget"](https://github.com/cloudant/CDTDatastore/blob/master/CDTDatastore/CDTReplicator/CDTReplicator.m#L56). The points in the `CDTReplicator` lifecycle when this reference should be released are listed in those comments linked to.
If you create a `CDTReplicator` and it has not completed then there will still be a reference to it - as such you need the replicator to stop|complete|error before this reference will be released. I can't see from the analysis provided if the replication has already completed, but at least the cycle reported by the tooling is expected.

**Comment by navaneet** [comment] 2018-12-10 18:07
Thanks for the explanation, we will try to reproduce this issue with a smaller sample and see if it reoccurs.

**Closed** 2022-01-27 13:43 UTC
Labels: EOL
