### ISSUE TITLE
Assertion failure when stopping pull

### ISSUE THREAD

**Issue by joergbirkhold** [cloudant/CDTDatastore#383] opened 2017-09-06 16:14 UTC
If I am pulling about 5 DBs  simultaneously and then call stop on the pull replicator of one, I get an 
Assertion failure here:
TDPuller.m Line 140
- (void)startChangeTracker
{
    Assert(!_changeTracker);
...

CDT Version 1.2.1 iOS

**Comment by tomblench** [comment] 2017-09-06 16:18
@joergbirkhold can you share the code where you are creating and starting the replicators? It looks like there is some state being shared across these threads which shouldn't.

**Comment by joergbirkhold** [comment] 2017-09-06 17:37
I tried various dispatch attempts, right now I do the following:

-(void)replicatorDidChangeState:(CDTReplicator *)replicator
//-------------
// svo is a simple class holding refs for the replication
//Code for starting:
dispatch_async(dispatch_get_main_queue(), ^{
	NSError* error;
    svo.database = [self.server datastoreNamed:svo.localDBName error:&error];
    if (!svo.database) {
        NSLog(@"%@",[NSString stringWithFormat:@"Couldn't create local database. %@ %@",svo.sourceName,error.localizedDescription]);
        return;
    }
    svo.pullrepconfig = [CDTPullReplication replicationWithSource:turl target:svo.database];
    svo.repfactory = [[CDTReplicatorFactory alloc] initWithDatastoreManager:self.server];
    NSError *error = nil;
    svo.pull = [svo.repfactory oneWay:svo.pullrepconfig error:&error];
    svo.pull.delegate = svo;
    error = nil;
    if (![svo.pull startWithError:&error]){
            NSLog(@"Error starting replication: %@",error.localizedDescription);
    }
 });
//-------------
//Code for stopping:
pull is a reference to the replicator
if(svo.pull && svo.pullStatus == CDTReplicatorStateStarted ){
       dispatch_async(dispatch_get_main_queue(), ^{
           NSLog(@"dispatching stop for %@",svo.sourceName);
                [svo.pull stop];
        });
}

Also it is strange that sometimes the delegate gets the state "CDTReplicatorStateStopped" 2 times in the method

**Comment by tomblench** [comment] 2017-09-06 20:00
@joergbirkhold I don't see "about 5" different pull replications there, is there a loop or an array which controls the different replications? Does svo.pull get overwritten with different replicators? I would expect to see you maintaining an array or some other data structure to refer to your multiple replicators.

**Comment by joergbirkhold** [comment] 2017-09-07 07:20
oh yes of course I thought this is obvious. I maintain an array of svo's. 
I tried to start the replicators with a loop or by separately starting. All the same effect.
svo.pull does not get overwritten. 
furthermore the app is running since years with couchcocoa.
this issue arises after moving to CDTDataStore.
Can there be a race condition in CDTReplicator? I now saw in a crash that it was executing line 405:
 [self.tdReplicator stop];
but self.state was CDTReplicatorStateStopped

**Comment by tomblench** [comment] 2017-09-07 12:18
I'm having trouble reproducing your issue. Note that you don't have to start your replicators in an async block. They can be started on the main thread because they are async - you can use a busy-wait loop or a completion handler block to assert when the replicator has finished.

You can see an example of the completion handler block method in the [sample app](https://github.com/cloudant/CDTDatastore/blob/master/Project/Project/CDTViewController.m#L182) - in this case a pull replication is started when the user clicks/taps the button, on completion of that a push replication is started, and then on completion of that the UI is updated. Of course you can skip the push replication part if it's not appropriate.

**Comment by tomblench** [comment] 2017-09-07 12:22
@joergbirkhold OK I have just managed to reproduce your issue, will continue investigating

**Comment by joergbirkhold** [comment] 2017-09-07 13:22
@tomblench That is (good) to hear, I was searching for hours and couldn't find anything on my side.
Let me know if I can help in any way.

**Comment by tomblench** [comment] 2017-09-07 14:52
I've opened #384 which will get prioritised on our backlog. It doesn't look like a trivial fix so it might take us a while.

**Comment by tomblench** [comment] 2017-11-06 09:31
Tracking this through #384 now, closing

**Closed by tomblench** 2017-11-06 09:31 UTC
Labels: bug
