### ISSUE TITLE
ReplicationAcceptance test failing with IAM key

### ISSUE THREAD

**Issue by emlaver** [cloudant/CDTDatastore#392] opened 2017-10-20 15:32 UTC
When running IAM-enabled tests, `testRemoteLastSequenceValueAfterPushReplication` intermittently fails.  It may be a latency issue since we test with CouchDB on sync002 for non-IAM and testy025/clientlibs-test for IAM.

```

ReplicationAcceptance
  testRemoteLastSequenceValueAfterPushReplication, ((localLastSequence) != nil) failed
  /Users/cloudantsync/jenkins-ios/workspace/enable-and-jenkins-test-IAM-Y2WEQZR5QS7CHU7CMGCWAILHKF2FH4XE2WEKCDVCPIUHD6R67HPQ/CDTDatastoreReplicationAcceptanceTests/ReplicationAcceptance.m:1747

    XCTAssertNotNil(localLastSequence);
    XCTAssertNotNil(jsonResponse[@"source_last_seq"]);

  testRemoteLastSequenceValueAfterPushReplication, ((localLastSequence[@"source_last_seq"]) equal to (jsonResponse[@"source_last_seq"])) failed: ("(null)") is not equal to ("3005") - local: (null), remote response {
  /Users/cloudantsync/jenkins-ios/workspace/enable-and-jenkins-test-IAM-Y2WEQZR5QS7CHU7CMGCWAILHKF2FH4XE2WEKCDVCPIUHD6R67HPQ/CDTDatastoreReplicationAcceptanceTests/ReplicationAcceptance.m:1750

    XCTAssertEqualObjects(localLastSequence[@"source_last_seq"], jsonResponse[@"source_last_seq"],
                          @"local: %@, remote response %@", localLastSequence, jsonResponse);
}


Executed 45 tests, with 2 failures (0 unexpected) in 6280.861 (6280.884) seconds
```

**Comment by tomblench** [comment] 2017-11-06 14:21
Closing, this is a dupe of #395

**Closed by tomblench** 2017-11-06 14:21 UTC
Labels: testing
