### ISSUE TITLE
Getting crash on calling listIndexes

### ISSUE THREAD

**Issue by navaneet** [cloudant/CDTDatastore#417] opened 2018-04-02 15:10 UTC
Hi, we are using the latest version of CDTDatastore version 2.0.0 with swift. However when we call

`self.dataStore?.listIndexes()`

It results in the following crash

Execution was interrupted, reason: EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)

We have been able to call all other CDTDatastore methods needed for our purpose except this one. Please help. Also this exception has been persistent in the earlier versions of the library also.

We have tried  accessing the indexes the following way also, still no luck
 ```
     do {
            let i =  try CDTQIndexManager(using: self.dataStore!)
            i.listIndexes()
            } catch {}

```

**Comment by tomblench** [comment] 2018-04-06 10:27
This works for us in objective-c although we haven't tried in swift yet. See [here](https://gist.github.com/tomblench/e80581182d72deb148b60488bb47de73) for an example gist which works.

Can you provide any more information like backtrace? `Execution was interrupted, reason: EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)` is extremely generic and doesn't help us track down the issue.

**Comment by tomblench** [comment] 2018-04-06 11:03
OK I've reproduce on swift, digging into what's going wrong.

**Comment by tomblench** [comment] 2018-04-06 11:25
@navaneet the problem occurs in objective-c/swift bridging, because the return type of `listIndexes` is incorrectly declared [here](https://github.com/cloudant/CDTDatastore/blob/master/CDTDatastore/query/CDTDatastore+Query.h#L49).

For reference it should be declared as
```objc
- (NSDictionary<NSString *, NSDictionary *> *)listIndexes;
```
and you can patch it locally yourself if you need an urgent fix.

Hopefully we should be able to get a release done soon which fixes this.

**Comment by navaneet** [comment] 2018-04-06 14:32
I will wait for the official patch, thanks @tomblench

**Comment by tomblench** [comment] 2018-04-17 08:15
@navaneet we have just release 2.0.1 which contains a fix for this bug.

**Closed by tomblench** 2018-04-17 08:15 UTC

**Comment by navaneet** [comment] 2018-04-17 12:08
Thanks let me check.
