### ISSUE TITLE
How can we support multi peer replication with CDTDatastore

### ISSUE THREAD

**Issue by navaneet** [cloudant/CDTDatastore#451] opened 2019-02-06 16:35 UTC
### Explanation of the issue

Currently we are able to replicate from the cloud to the iOS devices using the replication which is working fine. Thanks for the wonderful support you guys provided earlier which made it possible and our clients happy.

Now we are doing some experiments around multi peer connectivity framework and replication in between iOS devices which are not necessarily connected to internet but, local wifi network, and for this we need your help with

https://developer.apple.com/videos/play/wwdc2014/709/

https://developer.apple.com/documentation/multipeerconnectivity 

https://nshipster.com/multipeer-connectivity/

@tomblench @ricellis Can you please provide your insights?

## Environment details
- iOS
    > 12

**Comment by ricellis** [comment] 2019-02-07 10:40
CDTDatastore (and sync-android) were designed to communicate with a remote CouchDB or Cloudant server via the replication protocol. In essence the pull replication source or push replication target must provide the HTTP API endpoints required by the CouchDB replication protocol. There is no functionality built-in to the libraries for exposing these HTTP endpoints nor do we have plans to add this capability. Replication via alternative non-HTTP protocols is completely out of scope.

**Comment by navaneet** [comment] 2019-02-07 11:04
K thanks for the quick reply, is there a way to create a duplicate copy of a doc in datastore if say we get it from another source  E.g. (a socket event etc.) and we manually insert it into a datastore the same exact replica of the doc with it's revision history intact ?

Just to be clear, we don't want to exactly create a new revision, to avoid document conflicts later on however we do need to be able to create an exact replica doc from one datastore to another by manually inserting it into the datastore.

Can you provide something like a copy function as outlined in the couchdb docs ?

https://couchdb-13.readthedocs.io/en/latest/api/documents/#copying-from-a-specific-revision

Also, I do remember the android version of the library having a forceInsert API for the datastore but, the same is not exposed in CDTDatastore.

 Can you please advice on the risks involved if any or any other alternatives?

**Comment by ricellis** [comment] 2019-02-18 16:52
>is there a way to create a duplicate copy of a doc in datastore if say we get it from another source E.g. (a socket event etc.) and we manually insert it into a datastore the same exact replica of the doc with it's revision history intact ?

I don't think so, the library's replicator inserts revision history via [TD_Database's forceInsert](https://github.com/cloudant/CDTDatastore/blob/master/CDTDatastore/touchdb/TD_Database%2BInsertion.h#L43), but I don't think this internal API is accessible.

>Can you provide something like a copy function as outlined in the couchdb docs ?

CouchDB's `COPY {db}/{doc}` doesn't preserve any revision history, so I don't think this is what you want.

>Also, I do remember the android version of the library having a forceInsert API for the datastore but, the same is not exposed in CDTDatastore.

Correct, in response to a feature request we reluctantly exposed an advanced [`Database` interface with a `createWithHistory` API](https://static.javadoc.io/com.cloudant/cloudant-sync-datastore-core/2.4.0/com/cloudant/sync/documentstore/advanced/Database.html).

>Can you please advice on the risks involved if any or any other alternatives?

As I said this is outside the scope of what the library was intended for and beyond what we have tested (or will test) so is always likely to be brittle. There are, I think, three possibilities:
1. You provide an HTTP API that the library replicator can pull from. This is low-risk from the library perspective as it will be treated as any other replication source, assuming the HTTP API honours the CouchDB replication protocol.
1. You open a PR or make a feature request for adding an advanced CDTDatastore API with `createWithHistory` similar to what was done for sync-android. This is much riskier because the interaction of additional `forceInsert` operations on the device DB outside the remit of the existing replicator is unknown territory. Full disclosure - a feature request for this would not be high on our priority list.
1. In the special case where the document does not exist in the local datastore you could send and insert the revs in order to recreate the tree, but I think this is almost uselessly fragile.

I don't think there is another alternative if you want to maintain the revision history.

**Comment by navaneet** [comment] 2019-02-20 15:04
Ok, thanks for your inputs, let me discuss this with my team, will get back to you if any further help is needed.

**Closed** 2022-01-27 13:43 UTC
Labels: EOL
